# Generated by Django 5.1.6 on 2025-07-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
