# Generated by Django 5.2.4 on 2025-07-15 17:22

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration', models.DurationField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=2, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('return_users', models.IntegerField(default=0)),
                ('top_selling_products', models.JSONField(default=dict)),
                ('category_distribution', models.JSONField(default=dict)),
                ('cart_abandonment_rate', models.FloatField(default=0)),
                ('items_per_cart', models.FloatField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='analytics_a_date_5d846a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_count', models.IntegerField()),
                ('average_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_r_date_f7d2a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('pages_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'Product View'), ('cart_add', 'Add to Cart'), ('cart_remove', 'Remove from Cart'), ('purchase', 'Purchase'), ('search', 'Search'), ('wishilist_add', 'Add to Wishlist')], max_length=20)),
                ('search_query', models.CharField(max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('page_views', models.IntegerField(default=0)),
                ('time_spent', models.DurationField(default=datetime.timedelta)),
                ('entry_page', models.CharField(max_length=255)),
                ('exit_page', models.CharField(blank=True, max_length=255)),
                ('search_queries', models.JSONField(default=list)),
                ('filter_usage', models.JSONField(default=dict)),
                ('cart_additions', models.IntegerField(default=0)),
                ('cart_removals', models.IntegerField(default=0)),
                ('cart_abandonment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='analytics_u_session_86965d_idx'), models.Index(fields=['created_at'], name='analytics_u_created_659b68_idx')],
            },
        ),
    ]
