name: stylish_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.0.0

  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  fl_chart: ^1.0.0
  intl: ^0.20.2
  equatable: ^2.0.7
  retry: ^3.1.2
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  web: ^1.1.0
  file_picker: ^10.2.0
  uuid: ^4.5.1
  flutter_staggered_animations: ^1.1.1
  syncfusion_flutter_charts: ^29.2.10
  animate_do: ^4.2.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  universal_html: ^2.2.4
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  lottie: ^3.3.1
  flutter_hooks: ^0.21.2
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  dotted_border: ^3.0.1
  image: ^4.5.4
  mime: ^2.0.0
  dio: ^5.8.0+1

  connectivity_plus: ^6.1.4
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_9pt-Bold.ttf
          weight: 700

    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
