# Generated by Django 5.1.6 on 2025-08-04 05:04

from django.db import migrations

def create_chat_assistant_agent(apps, schema_editor):
    """
    Creates the default Chat Assistant Agent if it doesn't exist.
    """
    Agent = apps.get_model('ai_agents', 'Agent')
    db_alias = schema_editor.connection.alias

    if not Agent.objects.using(db_alias).filter(agent_type='chat_assistant').exists():
        Agent.objects.using(db_alias).create(
            name='Chat Assistant',
            agent_type='chat_assistant',
            description='Handles conversational queries from the admin dashboard.',
            is_active=True,
            configuration={}
        )

def remove_chat_assistant_agent(apps, schema_editor):
    """
    Removes the Chat Assistant Agent.
    """
    Agent = apps.get_model('ai_agents', 'Agent')
    db_alias = schema_editor.connection.alias
    Agent.objects.using(db_alias).filter(agent_type='chat_assistant').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_chat_assistant_agent, remove_chat_assistant_agent),
    ]