# Generated by Django 5.1.6 on 2025-08-04 05:04


from django.db import migrations

AGENT_DEFINITIONS = [
    {
        'name': 'Inventory Manager',
        'agent_type': 'inventory_manager',
        'description': 'Monitors stock levels, analyzes inventory turnover, and provides restocking recommendations.',
        'is_active': True,
        'configuration': {
            'low_stock_threshold_factor': 1.5,
            'sales_velocity_period_days': 30
        }
    },
    {
        'name': 'Sales Analyst',
        'agent_type': 'sales_analyst',
        'description': 'Analyzes sales data, identifies trends, and forecasts future sales performance.',
        'is_active': True,
        'configuration': {
            'trend_analysis_period_days': 90,
            'forecast_horizon_days': 30
        }
    }
]

def create_initial_agents(apps, schema_editor):
    """
    Creates the default Inventory Manager and Sales Analyst agents if they don't exist.
    """
    Agent = apps.get_model('ai_agents', 'Agent')
    db_alias = schema_editor.connection.alias

    for agent_def in AGENT_DEFINITIONS:
        if not Agent.objects.using(db_alias).filter(agent_type=agent_def['agent_type']).exists():
            Agent.objects.using(db_alias).create(
                name=agent_def['name'],
                agent_type=agent_def['agent_type'],
                description=agent_def['description'],
                is_active=agent_def['is_active'],
                configuration=agent_def['configuration']
            )

def remove_initial_agents(apps, schema_editor):
    """
    Removes the Inventory Manager and Sales Analyst agents.
    """
    Agent = apps.get_model('ai_agents', 'Agent')
    db_alias = schema_editor.connection.alias
    agent_types_to_remove = [agent['agent_type'] for agent in AGENT_DEFINITIONS]
    Agent.objects.using(db_alias).filter(agent_type__in=agent_types_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_auto_20250804_0504'),
    ]

    operations = [
        migrations.RunPython(create_initial_agents, remove_initial_agents),
    ]

