# Generated by Django 5.1.6 on 2025-08-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_auto_20250804_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='metadat',
            new_name='metadata',
        ),
    ]
